#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: akbar
 * Date: 27.05.15
 * Time: 11:24
 */

require __DIR__ . '/vendor/autoload.php';

define("MIGRATIONS_PATH", __DIR__ . '/app/kurma/database/migrations');
define("SEEDS_PATH", __DIR__ . '/app/kurma/database/seeds');

class Database {

    public function __construct($args){
        $this->args = $args;
        $setup = new \kurma\Setup();
    }

    public function run(){
        if(count($this->args) <= 1){
            $this->help();
        } else{
            switch($this->args[1]) {
                case "migrate":
                    $files = glob(MIGRATIONS_PATH . '/*.php');
                    $this->doMigrateSeed($files, 'migrations');
                    break;
                case "seed":
                    $files = glob(SEEDS_PATH . '/*.php');
                    $this->doMigrateSeed($files, 'seeds');
                    break;
                case "help":
                    $this->help();
                    break;
            }
        }
    }

    private function help(){
        echo "usage: php " . $this->args[0] . " <command> [migrate | seed]\n";
    }

    private function doMigrateSeed($files, $mode){
        foreach($files as $file){

            $class = "\\kurma\\database\\$mode\\".basename($file, '.php');

            $object = new $class;
            $object->run();

            echo "do $mode for table: ".basename($file, '.php')."\n";
        }
    }
}

$db = new Database($argv);
$db->run();